repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language: python
        exclude: ^migrations/
-   repo: local
    hooks:
    -   id: lint back
        name: lint front
        language: system
        entry: npm run lint
        pass_filenames: false
        always_run: true
    -   id: test
        name: test
        language: system
        entry: npm run test
        pass_filenames: false
        always_run: true
