"""add reviews table

Revision ID: c19d3bbd30f5
Revises: 3b838376971d
Create Date: 2022-09-20 23:43:13.104001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19d3bbd30f5'
down_revision = '3b838376971d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('help_desc', sa.Text(length=300), nullable=False),
    sa.Column('time_option', sa.Text(length=10), nullable=False),
    sa.Column('contacts', sa.Text(length=300), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
